pen_dataprodukt:
  target: pen_oracle
  outputs:
    pen_oracle:
      type: oracle
      port: 1521
      threads: 2
      protocol: tcp
      service: "{{env_var('DBT_ENV_SERVICE_NAME', 'pen_q2_ha')}}"
      database: "{{env_var('DBT_ENV_DATABASE', 'pen_q2_ha')}}"
      schema: pen_dataprodukt
      host: "{{env_var('DBT_ENV_SECRET_HOST')}}"
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
