pen_dataprodukt:
  target: pen_q2
  outputs:
    pen_q2:
      type: oracle
      port: 1521
      threads: 2
      protocol: tcp
      service: pen_q2_ha
      database: pen_q2_ha
      schema: pen_dataprodukt
      host: "{{env_var('DBT_ENV_SECRET_HOST')}}"
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
