version: 2

sources:
  - name: pen
    schema: pen
    tables:
      - name: t_beregning
      - name: t_beregning_info
      - name: t_beregning_res
      - name: t_kravhode
      - name: t_pen_under_utbet
      - name: t_uttaksgrad
      - name: t_vedtak
      - name: t_vilkar_vedtak
      - name: t_ytelse_komp
      - name: t_person
      - name: t_person_grunnlag
      - name: t_person_det
      - name: t_beholdning
      - name: t_min_pen_niva
      - name: t_inntekt
      - name: t_anvendt_trygdetid
      - name: t_brok
      - name: t_krav_arsak
      - name: t_sak
      - name: t_kravlinje
      - name: t_kravlinje_s
      - name: t_pen_org_enhet
      - name: t_k_kravlinje_t
      - name: t_beregning_2011
