# uv.lock i dette repoet brukes bare lokalt
# dbt kjører i Airflow med dbt-imaget fra dvh-images

version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/dbt"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆ "
    cooldown:
      default-days: 7
    groups:
      pip:
        patterns:
        - '*'
